export enum ErrorCode {
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    UNAUTHORIZED = 'UNAUTHORIZED',
    INVALID_TOKEN = 'INVALID_TOKEN',
    EXPIRED_TOKEN = 'EXPIRED_TOKEN',
    GENERIC = 'GENERIC',
    INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
    UNIQUE_USER_VALUE_CONSTRAINT = 'UNIQUE_USER_VALUE_CONSTRAINT',
}
